--EJERCICIO 1
SELECT D.DEPT_NO, D.DNOMBRE
FROM DEPART D
WHERE D.DEPT_NO IN(SELECT DEPT_NO
                 FROM EMPLE
                 WHERE COMISION_PCT IS NOT NULL)
GROUP BY DEPT_NO, DNOMBRE;

/*SELECT DISTINCT DEPT_NO
FROM EMPLE
WHERE COMISION_PCT IS NOT NULL;*/
                
--EJERCICIO 2
SELECT DEPT_NO, DNOMBRE
FROM DEPART
WHERE DEPT_NO NOT IN(SELECT DEPT_NO
                    FROM EMPLE
                    WHERE COMISION_PCT IS NOT NULL)
GROUP BY DEPT_NO, DNOMBRE;


--EJERCICIO 3
SELECT DEPT_NO 
FROM DEPART
WHERE DEPT_NO=(SELECT DEPT_NO
                FROM EMPLE
                WHERE COUNT(EMP_NO)=MAX(EMP_NO);
                
--EJERCICIO 4
SELECT D.DEPT_NO, D.DNOMBRE
FROM DEPART D, EMPLE E
WHERE D.DEPT_NO=E.DEPT_NO
AND (SELECT DEPT_NO FROM EMPLE
WHERE MAX(OFICIO) IN 'PROGRAMADOS')
GROUP BY D.DEPT_NO, D.DNOMBRE; 
                
                