--EJRECICIO 8
CREATE INDEX IND_EMP_DEPT
ON EMPLE(DEPT_NO);

--EJERCICIO 9

DESC USER_INDEXES;

SELECT INDEX_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME= 'EMPLE';

--EJERCICIO 10

DROP INDEX IND_EMP_DEPT;

--EJECICIO 11

CREATE INDEX IND_DEPT_NOMBRE
ON DEPART(UPPER(DNOMBRE));

--EJERCICIO 13
ALTER INDEX IND_DEPT_NOMBRE MONITORING USAGE;

ALTER INDEX IND_DEPT_NOMBRE NOMONITORING USAGE;

--EJERCICIO 14
DESC USER_INDEXES;
SELECT MONITORING
FROM USER_INDEXES;
--EJERCICIO 15

CREATE SYNONYM DEP
FOR DEPART;

RENAME DEPARTAMENOTS TO DEPARTAMENTOS;

DESC USER_SYNONYMS;

SELECT SYNONYM_NAME
FROM USER_SYNONYMS
WHERE SYNONYM_NAME='DEP'
;

--EJERCICIO 16

SELECT SYNONYM_NAME
FROM USER_SYNONYMS;

DROP SYNONYM DEP;
